# Generated by Django 5.2.7 on 2025-10-07 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TermsAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "terms_version",
                    models.CharField(max_length=20, verbose_name="Versão dos Termos"),
                ),
                (
                    "acceptance_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Aceite"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms_acceptances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aceite dos Termos",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "terms_version"),
                        name="unique_user_terms_version",
                    )
                ],
            },
        ),
    ]
