# Generated by Django 5.2.7 on 2025-10-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_termsacceptance"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistprofile",
            name="role",
            field=models.CharField(
                choices=[("OWNER", "Dono"), ("ARTIST", "Artista")],
                default="ARTIST",
                max_length=20,
                verbose_name="Função",
            ),
        ),
    ]
