# Generated by Django 5.2.7 on 2025-10-09 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_invitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artist_profiles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendente"),
                    ("ACCEPTED", "Aceito"),
                    ("REJECTED", "Rejeitado"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="artistprofile",
            unique_together={("user", "studio")},
        ),
    ]
