# Generated by Django 5.2.7 on 2025-10-11 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_artistprofile_user_alter_invitation_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_time", models.DateTimeField(verbose_name="Início do Bloqueio")),
                ("end_time", models.DateTimeField(verbose_name="Fim do Bloqueio")),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("BREAK", "Intervalo"),
                            ("ART_CREATION", "Criação de Arte"),
                            ("DAY_OFF", "Folga"),
                            ("OTHER", "Outro"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="Tipo de Bloqueio",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="Motivo"),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_blocks",
                        to="api.artistprofile",
                        verbose_name="Artista",
                    ),
                ),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_blocks",
                        to="api.studio",
                        verbose_name="Estúdio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloqueio de Tempo",
                "verbose_name_plural": "Bloqueios de Tempo",
                "ordering": ("-start_time",),
            },
        ),
    ]
