# Generated by Django 5.2.7 on 2025-10-12 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_timeblock"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("photo", models.ImageField(upload_to="client_photos/%Y/%m/")),
                (
                    "photo_type",
                    models.CharField(
                        choices=[("REF", "Referência"), ("DONE", "Trabalho Concluído")],
                        max_length=4,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.appointment",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="api.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
