# Generated by Django 5.2.7 on 2025-10-12 23:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_clientphoto"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("ANAM", "Anamnese"),
                            ("CONS", "Termo de Consentimento"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "unique_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("form_data", models.JSONField(default=dict)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("signature_data", models.TextField(blank=True)),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="consent_forms/%Y/%m/"
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.appointment",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="api.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
